/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gnuton_jni_qtmyobjWrapper */

#ifndef _Included_org_gnuton_jni_qtmyobjWrapper
#define _Included_org_gnuton_jni_qtmyobjWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gnuton_jni_qtmyobjWrapper
 * Method:    priority
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gnuton_jni_qtmyobjWrapper_priority
  (JNIEnv *, jobject);

/*
 * Class:     org_gnuton_jni_qtmyobjWrapper
 * Method:    setPriority
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_gnuton_jni_qtmyobjWrapper_setPriority
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
