/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gnuton_jni_wrappers_QtCoreApplicationWrapper */

#ifndef _Included_org_gnuton_jni_wrappers_QtCoreApplicationWrapper
#define _Included_org_gnuton_jni_wrappers_QtCoreApplicationWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gnuton_jni_wrappers_QtCoreApplicationWrapper
 * Method:    startApplication
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gnuton_jni_wrappers_QtCoreApplicationWrapper_startApplication
  (JNIEnv *, jobject);

/*
 * Class:     org_gnuton_jni_wrappers_QtCoreApplicationWrapper
 * Method:    stopApplication
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gnuton_jni_wrappers_QtCoreApplicationWrapper_stopApplication
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
